### ISSUE TITLE
I need a help for understanding 'get_exp_sens' function

### ISSUE THREAD

**Issue by tootouch** [chihkuanyeh/saliency_evaluation#2]
Hi, 

First of all, I really appreciate for your contributions of this paper. This paper was so interesting to me.

I was wondering your code about '[get_exp_sens](https://github.com/chihkuanyeh/saliency_evaluation/blob/44a66e2531f30b803be3bf5b0786971b7e7f72a1/infid_sen_utils.py#L301)' function in `saliency_evaluation/infid_sen_utils.py`.

```python
def get_exp_sens(X, model, expl,exp, yy, pdt, sg_r,sg_N,sen_r,sen_N,norm,binary_I,given_expl):
    max_diff = -math.inf
    for _ in range(sen_N):
        sample = torch.FloatTensor(sample_eps_Inf(X.cpu().numpy(), sen_r, 1)).cuda()
        X_noisy = X + sample
        expl_eps, _ = get_explanation_pdt(X_noisy, model, yy, exp, sg_r, sg_N,
                                     given_expl=given_expl, binary_I=binary_I)
        max_diff = max(max_diff, np.linalg.norm(expl-expl_eps)) / norm
    return max_diff
```

I understood `maximum sensitivity` is defined as follow:

![image](https://user-images.githubusercontent.com/37654013/106702253-5fb11600-662b-11eb-8584-1e1b0ca16b4f.png)

However, `max_diff` is defined by dividing **norm** in your code, where the **norm** is L2 norm of `expl`. But the **norm** does not exist in your paper.

If you want to use norm for scaling values, I think that `max_diff` should be defined as follow:

```python
max_diff = max(max_diff, np.linalg.norm(expl-expl_eps) / norm) 
```

It cannot obtain `max_diff` using maximum delta when **norm** is dividing max() because `max(max_diff, np.linalg.norm(expl-expl_eps) / norm) ` is always lower than `np.linalg.norm(expl-expl_eps) `.

I want to know your opinion.
Thank you.

**Comment by chihkuanyeh** [comment]
Hi TooTouch, 

Sorry for the late reply, I think your observation is correct.
It seems to be a mistake on our end.
Let me try to update the code and resulting numbers, thanks for pointing this out.
